#ARDUINO_DIR  = /Users/kaaninan/Desktop/make/Java
ARDMK_DIR = /Users/kaaninan/Desktop/make

AVR_TOOLS_DIR = ../../Arduino/avr
ARDUINO_LIB_PATH = ../../Arduino/libraries
ARDUINO_CORE_PATH = ../../Arduino/arduino
ARDUINO_VAR_PATH = ../../Arduino/variants
BOARDS_TXT = ../../Arduino/boards.txt
BOOTLOADER_PARENT = ../../Arduino/bootloader
ARDUINO_VERSION = ../../Arduino/version.txt
AVRDUDE_CONF = ../../Arduino/avr/etc/avrdude.conf

BOARD_TAG    = uno
ARDUINO_PORT = /dev/cu.usbmodem1421
ARDUINO_LIBS =

include ../../arduino-mk/Arduino.mk